Fix error when response is missing `included`
This fixes the following error when the response from the server does
not have the `included` key:

TypeError: Cannot read properties of undefined (reading 'included')

When missing, the value already defaults to an empty array so this
should be safe when it's "undefined" as well.